[package]
name = "i2eye"
version = "0.5.0"
authors = ["sourcepirate <plasmashadowx@gmail.com>"]

[dependencies]
reqwest = "0.8.4"
hyper = "0.11.15"
log = "0.4.1"
env_logger = "0.5.3"
time = "0.1.39"
futures = "0.1.18"
url = "1.6.0"
clap = "2.29.2"